import turtle as  tl
tl.Screen().bgcolor("black")
t=tl.Turtle()
def logo(a,b):
    t.color(b)
    t.begin_fill()
    t.circle(a)
    t.end_fill()
t.penup()
t.goto(-30,-280)
t.pendown()
logo(250,'red')
t.goto(-30,-240)
logo(210,'white')
t.goto(-30,-200)
logo(170,'red')
t.goto(-30,-160)
logo(130,'blue')
t.goto(-153,11)
t.begin_fill()
t.color('white')
for i in range(5):
    t.forward(245)
    t.right(144)
t.end_fill()
tl.done()